### ISSUE TITLE
User Story: Viewing listed products

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/loketable#2]
As a **user** I can **visit the home page** so that **see the list of offered products**

## Acceptance Criteria
AC 1: Landing page welcomes user and gives the option to register, log in and view products
AC 2: When a user is logged in lands directly in listed products page
AC 3: Products card contain a photo, the title, location, price per unit, category and the name of the producer.
AC 4: All elements are clickable and will link to the product details or producer profile respectively.

## Tasks:
- [x] Create view for home
- [x] Create view for products list
- [x] Create templates for home and producrs
- [x] Create urls
